Fix compilation error: comment out empty link field in location
The brilliant-cv template does not accept empty link values. Commented out
the link field for the location custom field since Seattle, WA doesn't need
a hyperlink.